### ISSUE TITLE
ArrayOutOfBoundsException in /PerWorldChat_v1.2.phar/src/PerWorldChat/EventListener

### ISSUE THREAD

**Issue by RocoWayne** [EvolSoft/PerWorldChat#3]
03.02 11:58:21 [Server] Server thread/NOTICE ArrayOutOfBoundsException: "Undefined offset: 20" (E_NOTICE) in "/PerWorldChat_v1.2.phar/src/PerWorldChat/EventListener" at line 32
03.02 11:58:21 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerChatEvent' to 'PerWorldChat v1.2': Undefined offset: 20 on PerWorldChat\EventListener

**Comment by Flavius12** [comment]
Thanks for this report. I'll fix this issue as I did on ServerAuth

**Comment by RocoWayne** [comment]
Any news?

**Comment by Flavius12** [comment]
Fixed in v1.3
